apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-user
  template:
    metadata:
      labels:
        app: container-user
    spec:
      containers:
        - name: container-user
          image: microservicos_docker-container_user
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: mysql-user-service
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_NAME
              value: adm_user
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - name: container-user-volume
              mountPath: /app
      volumes:
        - name: container-user-volume
          hostPath:
            path: /D:/microservicos_docker/servicoUser
---
apiVersion: v1
kind: Service
metadata:
  name: container-user-service
spec:
  type: ClusterIP
  selector:
    app: container-user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
